/**
 * Builds the AppSail deployment bundle into ./appsail-dist.
 *
 * Why this exists rather than deploying the project directory as-is:
 *
 *  1. AppSail requires node_modules inside the uploaded package (Catalyst does
 *     not run `npm install` remotely), but the Catalyst CLI zips every file
 *     holding an open handle each, and dies with EMFILE on Windows at ~8k
 *     files. The full tree is ~31k. Next's `output: "standalone"` traces only
 *     the modules actually reachable at runtime — ~1.7k files.
 *
 *  2. A custom server that calls `next()` pulls in Next's webpack/config
 *     machinery, which standalone deliberately does NOT trace (you get
 *     "Cannot find module './bundle5'"). Standalone sidesteps this by feeding
 *     a pre-computed config to NextServer directly. This script reuses the
 *     preamble Next generates — including that config — and appends a
 *     bootstrap that binds Catalyst per request, so we keep the request-scoped
 *     SDK context without needing `next()` or Express.
 *
 * Run via `npm run build:appsail` (which builds first).
 */
const fs = require("node:fs");
const path = require("node:path");
const { execFileSync } = require("node:child_process");

const ROOT = path.join(__dirname, "..");
const STANDALONE = path.join(ROOT, "dist", "standalone");
const OUT = path.join(ROOT, "appsail-dist");

function fail(message) {
  console.error(`build-appsail: ${message}`);
  process.exit(1);
}

if (!fs.existsSync(path.join(STANDALONE, "server.js"))) {
  fail('dist/standalone not found — run "npm run build" first (needs output: "standalone").');
}

// --- 1. Fresh staging dir -------------------------------------------------
fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(OUT, { recursive: true });
fs.cpSync(STANDALONE, OUT, { recursive: true });

// Standalone omits the static assets and public/ — they must be copied in.
fs.cpSync(path.join(ROOT, "dist", "static"), path.join(OUT, "dist", "static"), { recursive: true });
if (fs.existsSync(path.join(ROOT, "public"))) {
  fs.cpSync(path.join(ROOT, "public"), path.join(OUT, "public"), { recursive: true });
}
// The bundle is already built, so the preserve/predeploy hooks (npm install +
// next build) must not run against it — they'd reinstall the full dependency
// tree over the traced one.
const appConfig = JSON.parse(fs.readFileSync(path.join(ROOT, "app-config.json"), "utf8"));
delete appConfig.scripts;
fs.writeFileSync(path.join(OUT, "app-config.json"), JSON.stringify(appConfig, null, 1) + "\n");

// --- 2. Server entrypoint -------------------------------------------------
// Reuse Next's generated preamble verbatim (it declares `dir`, `hostname` and
// the fully-resolved `nextConfig`, and sets __NEXT_PRIVATE_STANDALONE_CONFIG),
// then replace its startServer() call with a Catalyst-aware one.
const generated = fs.readFileSync(path.join(STANDALONE, "server.js"), "utf8");
const marker = "process.env.__NEXT_PRIVATE_STANDALONE_CONFIG";
const markerIndex = generated.indexOf(marker);
if (markerIndex === -1) {
  fail("could not find __NEXT_PRIVATE_STANDALONE_CONFIG in Next's generated server.js — Next version change?");
}
const preamble = generated.slice(0, generated.indexOf("\n", markerIndex) + 1);

const bootstrap = `
// ---------------------------------------------------------------------------
// Catalyst-aware bootstrap (generated by scripts/build-appsail.js)
// ---------------------------------------------------------------------------
const http = require('node:http');
const { AsyncLocalStorage } = require('node:async_hooks');
const catalyst = require('zcatalyst-sdk-node');

// Catalyst's SDK binds identity per call via catalyst.initialize(req), which
// needs a real Node request — not the Fetch Request a Route Handler receives,
// and not available at all inside Server Components. So it's initialized once
// per request and published through an AsyncLocalStorage that lib/ reads back
// via getCatalystApp().
//
// The store hangs off globalThis under a Symbol.for key because this process
// loads the context module twice (once here, once inside the webpack bundle);
// two separate instances would mean the writer and readers never see each
// other. lib/catalystContext.js uses the identical key.
const CONTEXT_KEY = Symbol.for('ksp.catalystContext');
const catalystContext =
  globalThis[CONTEXT_KEY] ?? (globalThis[CONTEXT_KEY] = new AsyncLocalStorage());

// Next's own startServer() is used rather than driving NextServer directly:
// as of Next 13.5+ the static-asset routes (/_next/static/*) live in the
// router-server layer that startServer builds, so a bare
// NextServer.getRequestHandler() serves pages fine but 404s every stylesheet
// and client chunk — the app renders completely unstyled.
//
// startServer exposes no per-request hook, so http.createServer is patched
// first and the handler it's given is wrapped. That keeps all of Next's
// routing intact while still binding Catalyst around every request.
const originalCreateServer = http.createServer.bind(http);
http.createServer = function patchedCreateServer(optionsOrHandler, maybeHandler) {
  const hasOptions = typeof optionsOrHandler !== 'function';
  const options = hasOptions ? optionsOrHandler : undefined;
  const handler = hasOptions ? maybeHandler : optionsOrHandler;
  if (typeof handler !== 'function') {
    return hasOptions ? originalCreateServer(options) : originalCreateServer();
  }
  // Build assets need no Catalyst context, so they skip initialization: it's
  // pure overhead on every stylesheet/chunk, and a failure there would take
  // the whole page's styling down rather than just its data.
  const isStaticAsset = (url) =>
    url.startsWith('/_next/static/') || url === '/favicon.ico';

  const wrapped = (req, res) => {
    if (isStaticAsset(req.url || '')) {
      handler(req, res);
      return;
    }
    let catalystApp;
    try {
      catalystApp = catalyst.initialize(req);
    } catch (err) {
      // Only reachable outside real Catalyst infra — fail this one request
      // rather than taking down the process.
      console.error('Catalyst SDK initialization failed for this request:', err);
      res.statusCode = 500;
      res.end('Catalyst SDK failed to initialize for this request.');
      return;
    }
    catalystContext.run(catalystApp, () => handler(req, res));
  };
  return hasOptions ? originalCreateServer(options, wrapped) : originalCreateServer(wrapped);
};

require('next');
const { startServer } = require('next/dist/server/lib/start-server');

// AppSail injects the port to bind on; PORT/3000 are local fallbacks.
const listenPort =
  parseInt(process.env.X_ZOHO_CATALYST_LISTEN_PORT, 10) || parseInt(process.env.PORT, 10) || 3000;

// Next's own NaN guard for keepAliveTimeout lives below its startServer call,
// i.e. past the preamble we reuse — so it's repeated here.
if (Number.isNaN(keepAliveTimeout) || !Number.isFinite(keepAliveTimeout) || keepAliveTimeout < 0) {
  keepAliveTimeout = undefined;
}

startServer({
  dir,
  isDev: false,
  config: nextConfig,
  hostname,
  port: listenPort,
  allowRetry: false,
  keepAliveTimeout,
})
  .then(() => console.log('> Ready on port ' + listenPort + ' (appsail)'))
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
`;

fs.writeFileSync(path.join(OUT, "server.js"), preamble + bootstrap);

// --- 3. Runtime deps standalone can't trace -------------------------------
// zcatalyst-sdk-node is only referenced from the server entrypoint above, so
// Next's tracing never sees it.
const pkgPath = path.join(OUT, "package.json");
const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf8"));
pkg.scripts = { start: "node server.js" };
delete pkg.devDependencies;
// Declared for reference only — node_modules is vendored, AppSail won't install.
pkg.dependencies = { next: pkg.dependencies?.next ?? "14.2.35", "zcatalyst-sdk-node": "^3.4.0" };
fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + "\n");

// Installed into a scratch dir and merged in, rather than `npm install` inside
// the bundle: npm reconciles the whole dependency list, which would reinstall
// the full `next` package (~6.4k files) over the traced copy and put us back
// over the EMFILE threshold.
const scratch = path.join(require("node:os").tmpdir(), "ksp-appsail-deps");
fs.rmSync(scratch, { recursive: true, force: true });
fs.mkdirSync(scratch, { recursive: true });
fs.writeFileSync(
  path.join(scratch, "package.json"),
  JSON.stringify({ name: "ksp-appsail-deps", version: "1.0.0", private: true }) + "\n"
);
console.log("build-appsail: resolving zcatalyst-sdk-node...");
execFileSync("npm", ["install", "zcatalyst-sdk-node@^3.4.0", "--omit=dev", "--no-package-lock"], {
  cwd: scratch,
  stdio: "inherit",
  shell: process.platform === "win32",
});
// force:false keeps Next's traced modules authoritative on any overlap.
fs.cpSync(path.join(scratch, "node_modules"), path.join(OUT, "node_modules"), {
  recursive: true,
  force: false,
  errorOnExist: false,
});
fs.rmSync(scratch, { recursive: true, force: true });

function countFiles(dir) {
  let total = 0;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    total += entry.isDirectory() ? countFiles(path.join(dir, entry.name)) : 1;
  }
  return total;
}
console.log(`build-appsail: bundle ready at appsail-dist (${countFiles(OUT)} files)`);
